# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem "couchbase", "3.0.0.beta.1"
gem "sinatra"
gem "sinatra-contrib"
