# frozen_string_literal: true

source "https://rubygems.org"

gem "couchbase", "3.0.0"
# Use latest stable build from snapshot repository.
# Note Ruby ABI version in URL (other available 2.5.0, 2.6.0)
# gem "couchbase", "~> 3.0.1.snapshot", :source => "https://sdk-snapshots.couchbase.com/ruby/2.7.0/"

gem "sinatra"

# dependencies of importer.rb
gem "goodreads"
gem "progressbar"
